/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Robot.Interface;


/**
 *
 * @author Usuario
 */
public class Questionario extends javax.swing.JFrame {

    /**
     * Creates new form Questionario
     */
    public Questionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sclPane = new javax.swing.JScrollPane();
        jpQuestionario = new javax.swing.JPanel();
        lblP1 = new javax.swing.JLabel();
        jbtnSim1 = new javax.swing.JRadioButton();
        jbtnNao1 = new javax.swing.JRadioButton();
        lblP2 = new javax.swing.JLabel();
        jbtnSim2 = new javax.swing.JRadioButton();
        jbtnNao2 = new javax.swing.JRadioButton();
        lblP3 = new javax.swing.JLabel();
        jbtnSim3 = new javax.swing.JRadioButton();
        jbtnNao3 = new javax.swing.JRadioButton();
        lblP4 = new javax.swing.JLabel();
        jbtnSim4 = new javax.swing.JRadioButton();
        jbtnNao4 = new javax.swing.JRadioButton();
        lblP5 = new javax.swing.JLabel();
        jbtnSim5 = new javax.swing.JRadioButton();
        jbtnNao5 = new javax.swing.JRadioButton();
        lblP6 = new javax.swing.JLabel();
        jbtnSim6 = new javax.swing.JRadioButton();
        jbtnNao6 = new javax.swing.JRadioButton();
        lblP7 = new javax.swing.JLabel();
        jbtnSim7 = new javax.swing.JRadioButton();
        jbtnNao7 = new javax.swing.JRadioButton();
        lblP8 = new javax.swing.JLabel();
        jbtnSim8 = new javax.swing.JRadioButton();
        jbtnNao8 = new javax.swing.JRadioButton();
        lblP9 = new javax.swing.JLabel();
        jbtnSim9 = new javax.swing.JRadioButton();
        jbtnNao9 = new javax.swing.JRadioButton();
        lblP10 = new javax.swing.JLabel();
        jbtnSim10 = new javax.swing.JRadioButton();
        jbtnNao10 = new javax.swing.JRadioButton();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpQuestionario.setBackground(new java.awt.Color(128, 128, 128));
        jpQuestionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Questionário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jpQuestionario.setForeground(new java.awt.Color(255, 255, 255));

        lblP1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblP1.setForeground(new java.awt.Color(255, 255, 255));
        lblP1.setText("1. Surge o assunto investimento sua reação é positiva?");

        jbtnSim1.setBackground(new java.awt.Color(128, 128, 128));
        jbtnSim1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnSim1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSim1.setText("Sim");

        jbtnNao1.setBackground(new java.awt.Color(128, 128, 128));
        jbtnNao1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnNao1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNao1.setText("Não");

        lblP2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblP2.setForeground(new java.awt.Color(255, 255, 255));
        lblP2.setText("2. Você tem mais que 30 anos?");

        jbtnSim2.setBackground(new java.awt.Color(128, 128, 128));
        jbtnSim2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnSim2.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSim2.setText("Sim");

        jbtnNao2.setBackground(new java.awt.Color(128, 128, 128));
        jbtnNao2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnNao2.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNao2.setText("Não");

        lblP3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblP3.setForeground(new java.awt.Color(255, 255, 255));
        lblP3.setText("3. Ao investir seu dinheiro, você espera rendimentos?");

        jbtnSim3.setBackground(new java.awt.Color(128, 128, 128));
        jbtnSim3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnSim3.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSim3.setText("Sim");

        jbtnNao3.setBackground(new java.awt.Color(128, 128, 128));
        jbtnNao3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnNao3.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNao3.setText("Não");

        lblP4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblP4.setForeground(new java.awt.Color(255, 255, 255));
        lblP4.setText(" 4. E segurança?");

        jbtnSim4.setBackground(new java.awt.Color(128, 128, 128));
        jbtnSim4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnSim4.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSim4.setText("Sim");

        jbtnNao4.setBackground(new java.awt.Color(128, 128, 128));
        jbtnNao4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnNao4.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNao4.setText("Não");

        lblP5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblP5.setForeground(new java.awt.Color(255, 255, 255));
        lblP5.setText("5. Sua renda mensal é maior que R$ 2000,00 ?");

        jbtnSim5.setBackground(new java.awt.Color(128, 128, 128));
        jbtnSim5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnSim5.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSim5.setText("Sim");

        jbtnNao5.setBackground(new java.awt.Color(128, 128, 128));
        jbtnNao5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnNao5.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNao5.setText("Não");

        lblP6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblP6.setForeground(new java.awt.Color(255, 255, 255));
        lblP6.setText("6. Você investe hoje ?");

        jbtnSim6.setBackground(new java.awt.Color(128, 128, 128));
        jbtnSim6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnSim6.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSim6.setText("Sim");

        jbtnNao6.setBackground(new java.awt.Color(128, 128, 128));
        jbtnNao6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnNao6.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNao6.setText("Não");

        lblP7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblP7.setForeground(new java.awt.Color(255, 255, 255));
        lblP7.setText("<html>7. E nos últimos dois anos, você aplicou em produtos como ações:<br><p> LCI/LCA ou debêntures?</p> </html");

        jbtnSim7.setBackground(new java.awt.Color(128, 128, 128));
        jbtnSim7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnSim7.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSim7.setText("Sim");

        jbtnNao7.setBackground(new java.awt.Color(128, 128, 128));
        jbtnNao7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnNao7.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNao7.setText("Não");

        lblP8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblP8.setForeground(new java.awt.Color(255, 255, 255));
        lblP8.setText("<html>\n8. Você tem R$ 5000,00 e vem uma turbulencia no mercado<br> e reduz o seu dinheiro pela metade.\nVoce resgata na hora?\n\n</html>");

        jbtnSim8.setBackground(new java.awt.Color(128, 128, 128));
        jbtnSim8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnSim8.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSim8.setText("Sim");

        jbtnNao8.setBackground(new java.awt.Color(128, 128, 128));
        jbtnNao8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnNao8.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNao8.setText("Não");

        lblP9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblP9.setForeground(new java.awt.Color(255, 255, 255));
        lblP9.setText("9. Você ganhou na loteria, o seu desejo é ganhar mais?");

        jbtnSim9.setBackground(new java.awt.Color(128, 128, 128));
        jbtnSim9.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnSim9.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSim9.setText("Sim");

        jbtnNao9.setBackground(new java.awt.Color(128, 128, 128));
        jbtnNao9.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnNao9.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNao9.setText("Não");

        lblP10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblP10.setForeground(new java.awt.Color(255, 255, 255));
        lblP10.setText("10.  Você acompanha noticias econômicas?");

        jbtnSim10.setBackground(new java.awt.Color(128, 128, 128));
        jbtnSim10.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnSim10.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSim10.setText("Sim");

        jbtnNao10.setBackground(new java.awt.Color(128, 128, 128));
        jbtnNao10.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jbtnNao10.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNao10.setText("Não");

        btnEnviar.setBackground(new java.awt.Color(0, 51, 255));
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("ENVIAR");
        btnEnviar.setAutoscrolls(true);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpQuestionarioLayout = new javax.swing.GroupLayout(jpQuestionario);
        jpQuestionario.setLayout(jpQuestionarioLayout);
        jpQuestionarioLayout.setHorizontalGroup(
            jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblP5)
                    .addComponent(lblP6)
                    .addComponent(lblP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP7, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP10)
                    .addComponent(lblP9, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpQuestionarioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                                .addComponent(jbtnSim2)
                                .addGap(32, 32, 32)
                                .addComponent(jbtnNao2))
                            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                                .addComponent(jbtnSim3)
                                .addGap(32, 32, 32)
                                .addComponent(jbtnNao3))
                            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                                .addComponent(jbtnSim4)
                                .addGap(32, 32, 32)
                                .addComponent(jbtnNao4))
                            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                                .addComponent(jbtnSim5)
                                .addGap(32, 32, 32)
                                .addComponent(jbtnNao5))
                            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                                .addComponent(jbtnSim6)
                                .addGap(32, 32, 32)
                                .addComponent(jbtnNao6))
                            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                                .addComponent(jbtnSim7)
                                .addGap(32, 32, 32)
                                .addComponent(jbtnNao7))
                            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                                .addComponent(jbtnSim8)
                                .addGap(32, 32, 32)
                                .addComponent(jbtnNao8))
                            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                                .addComponent(jbtnSim9)
                                .addGap(32, 32, 32)
                                .addComponent(jbtnNao9))
                            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                                .addComponent(jbtnSim10)
                                .addGap(32, 32, 32)
                                .addComponent(jbtnNao10)))))
                .addGap(0, 0, 0))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpQuestionarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblP2)
                    .addComponent(lblP3)
                    .addComponent(lblP4)
                    .addGroup(jpQuestionarioLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jbtnSim1)
                        .addGap(32, 32, 32)
                        .addComponent(jbtnNao1))
                    .addGroup(jpQuestionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblP1)))
                .addGap(0, 0, 0))
        );
        jpQuestionarioLayout.setVerticalGroup(
            jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQuestionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNao1)
                    .addComponent(jbtnSim1))
                .addGap(29, 29, 29)
                .addComponent(lblP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNao2)
                    .addComponent(jbtnSim2))
                .addGap(18, 18, 18)
                .addComponent(lblP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNao3)
                    .addComponent(jbtnSim3))
                .addGap(29, 29, 29)
                .addComponent(lblP4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNao4)
                    .addComponent(jbtnSim4))
                .addGap(18, 18, 18)
                .addComponent(lblP5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNao5)
                    .addComponent(jbtnSim5))
                .addGap(29, 29, 29)
                .addComponent(lblP6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNao6)
                    .addComponent(jbtnSim6))
                .addGap(18, 18, 18)
                .addComponent(lblP7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNao7)
                    .addComponent(jbtnSim7))
                .addGap(29, 29, 29)
                .addComponent(lblP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNao8)
                    .addComponent(jbtnSim8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblP9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNao9)
                    .addComponent(jbtnSim9))
                .addGap(29, 29, 29)
                .addComponent(lblP10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpQuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNao10)
                    .addComponent(jbtnSim10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sclPane.setViewportView(jpQuestionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sclPane, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and jpQuestionario the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JRadioButton jbtnNao1;
    private javax.swing.JRadioButton jbtnNao10;
    private javax.swing.JRadioButton jbtnNao2;
    private javax.swing.JRadioButton jbtnNao3;
    private javax.swing.JRadioButton jbtnNao4;
    private javax.swing.JRadioButton jbtnNao5;
    private javax.swing.JRadioButton jbtnNao6;
    private javax.swing.JRadioButton jbtnNao7;
    private javax.swing.JRadioButton jbtnNao8;
    private javax.swing.JRadioButton jbtnNao9;
    private javax.swing.JRadioButton jbtnSim1;
    private javax.swing.JRadioButton jbtnSim10;
    private javax.swing.JRadioButton jbtnSim2;
    private javax.swing.JRadioButton jbtnSim3;
    private javax.swing.JRadioButton jbtnSim4;
    private javax.swing.JRadioButton jbtnSim5;
    private javax.swing.JRadioButton jbtnSim6;
    private javax.swing.JRadioButton jbtnSim7;
    private javax.swing.JRadioButton jbtnSim8;
    private javax.swing.JRadioButton jbtnSim9;
    private javax.swing.JPanel jpQuestionario;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP10;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblP3;
    private javax.swing.JLabel lblP4;
    private javax.swing.JLabel lblP5;
    private javax.swing.JLabel lblP6;
    private javax.swing.JLabel lblP7;
    private javax.swing.JLabel lblP8;
    private javax.swing.JLabel lblP9;
    private javax.swing.JScrollPane sclPane;
    // End of variables declaration//GEN-END:variables
}
